# Dockerfile.server
FROM rust:latest

# Create a new directory for the application
WORKDIR /usr/src/app

# Copy the necessary files for building the application
COPY . .

# Build the application in release mode
WORKDIR /usr/src/app/example

# RUN cargo build --release
ENV RUST_BACKTRACE=1


# Command to run the server
CMD ["cargo", "run", "--", "--mode", "server", "--identifier", "10", "--ips", "172.20.0.3:3000,172.20.0.2:3000"]